//! Guidelines output — human-first governance reference or setup guide.
//!
//! Two paths:
//! - No config: prescriptive quickstart showing how to set up ADR governance.
//! - Config present: complete governance reference derived from config +
//!   hardcoded rule catalog.
//!
//! Output targets humans reading a terminal, not LLMs. Uses headings,
//! bullet lists, and visual hierarchy.

use std::io::{self, Write};

use crate::config::Config;
use crate::model::{RelVerb, Tier};
use crate::rules::catalog::{self, RuleEntry};
use crate::rules::template::Budgets;

/// Print the setup guide when no `adr-fmt.toml` exists.
///
/// # Errors
///
/// Returns any write error from `w`, so a closed pipe surfaces as an
/// infrastructure error (AFM-0003:R1) instead of a panic.
pub fn print_setup_guide(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "adr-fmt — ADR Governance Tool")?;
    writeln!(w, "═══════════════════════════════")?;
    writeln!(w)?;
    writeln!(
        w,
        "No adr-fmt.toml found. Create one at your workspace root."
    )?;
    writeln!(
        w,
        "Discovery walks up from the current directory until adr-fmt.toml"
    )?;
    writeln!(w, "with a valid [corpus] table is found.")?;
    writeln!(w)?;
    writeln!(w, "QUICK START")?;
    writeln!(w, "───────────")?;
    writeln!(w)?;
    writeln!(w, "  1. Create adr-fmt.toml at the workspace root:")?;
    writeln!(w)?;
    writeln!(w, "     [corpus]")?;
    writeln!(w, "     root = \"docs/adr\"")?;
    writeln!(w)?;
    writeln!(w, "     [stale]")?;
    writeln!(w, "     directory = \"stale\"")?;
    writeln!(w)?;
    writeln!(w, "     [[domains]]")?;
    writeln!(w, "     prefix = \"CHE\"")?;
    writeln!(w, "     name = \"Cherry\"")?;
    writeln!(w, "     directory = \"cherry\"")?;
    writeln!(
        w,
        "     description = \"Architecture decisions for the example project.\""
    )?;
    writeln!(w, "     crates = [\"example-core\"]")?;
    writeln!(w)?;
    writeln!(
        w,
        "  2. Create your first ADR at docs/adr/cherry/CHE-0001-...md:"
    )?;
    writeln!(w)?;
    writeln!(w, "     # CHE-0001. Your First Decision")?;
    writeln!(w)?;
    writeln!(w, "     Date: 2026-04-27")?;
    writeln!(w, "     Last-reviewed: 2026-04-27")?;
    writeln!(w, "     Tier: B")?;
    writeln!(w, "     Status: Draft")?;
    writeln!(w)?;
    writeln!(w, "     ## Related")?;
    writeln!(w)?;
    writeln!(w, "     Root: CHE-0001")?;
    writeln!(w)?;
    writeln!(w, "     ## Context")?;
    writeln!(
        w,
        "     Why this decision exists and what problem it solves."
    )?;
    writeln!(w)?;
    writeln!(w, "     ## Decision")?;
    writeln!(w, "     R1 [5]: The specific rule or decision statement")?;
    writeln!(w)?;
    writeln!(w, "     ## Consequences")?;
    writeln!(
        w,
        "     What changes as a result of this decision being made."
    )?;
    writeln!(w)?;
    writeln!(w, "  3. Run: adr-fmt --lint")?;
    writeln!(w)?;
    writeln!(w, "MODES")?;
    writeln!(w, "─────")?;
    writeln!(w)?;
    writeln!(
        w,
        "  adr-fmt                       Print governance guidelines (this output)"
    )?;
    writeln!(w, "  adr-fmt --lint                Lint all ADRs")?;
    writeln!(
        w,
        "  adr-fmt --refs CHE-0001       Inbound references to an ADR"
    )?;
    writeln!(
        w,
        "  adr-fmt --context crate-name  Decision rules for a crate"
    )?;
    writeln!(w, "  adr-fmt --tree [DOMAIN]       Domain tree overview")?;
    writeln!(w)?;
    Ok(())
}

/// Print the full governance reference when config is present.
///
/// # Errors
///
/// Returns any write error from `w`, so a closed pipe surfaces as an
/// infrastructure error (AFM-0003:R1) instead of a panic.
pub fn print_governance(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(w, "ADR Governance Reference")?;
    writeln!(w, "════════════════════════")?;
    writeln!(w)?;
    writeln!(
        w,
        "Generated by adr-fmt. Single source of truth for all invariant rules."
    )?;
    writeln!(
        w,
        "For rationale and process guidance, see docs/adr/adr-fmt/."
    )?;
    writeln!(w)?;

    print_modes(w)?;
    print_domains(w, config)?;
    print_tiers(w)?;
    print_lifecycle(w)?;
    print_template(w)?;
    print_tagged_rules(w, config)?;
    print_relationships(w, config)?;
    print_naming(w)?;
    print_link_rules(w)?;
    print_stale(w, config)?;
    print_overrides(w, config)
}

fn print_rule_entries(w: &mut impl Write, entries: &[&RuleEntry]) -> io::Result<()> {
    for entry in entries {
        writeln!(w, "    {:<6}{}", entry.id, entry.summary)?;
        for line in entry.continuation {
            writeln!(w, "          {line}")?;
        }
    }
    Ok(())
}

fn print_modes(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "MODES")?;
    writeln!(w, "─────")?;
    writeln!(w)?;
    writeln!(
        w,
        "  (default)             Governance guidelines (this document)"
    )?;
    writeln!(
        w,
        "  --lint                Lint all ADRs, report diagnostics"
    )?;
    writeln!(
        w,
        "  --refs <ADR_ID>       Inbound references to an ADR (References + Supersedes)"
    )?;
    writeln!(
        w,
        "  --context <CRATE>     Decision rules applicable to a crate"
    )?;
    writeln!(w, "  --tree [DOMAIN]       Domain dependency tree")?;
    writeln!(w)?;
    writeln!(w, "  Exit codes: 0 = complete, 1 = infrastructure error")?;
    writeln!(w)?;
    Ok(())
}

fn print_domains(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(w, "DOMAINS")?;
    writeln!(w, "───────")?;
    writeln!(w)?;
    for domain in &config.domains {
        let marker = if domain.foundation {
            " ★ foundation"
        } else {
            ""
        };
        writeln!(w, "  {} ({}){marker}", domain.name, domain.prefix)?;
        let desc: String = domain
            .description
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(w, "    {desc}")?;
        writeln!(w, "    Directory: {}/", domain.directory)?;
        if !domain.crates.is_empty() {
            writeln!(w, "    Crates: {}", domain.crates.join(", "))?;
        }
        writeln!(w)?;
    }
    Ok(())
}

fn print_tiers(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "TIERS")?;
    writeln!(w, "─────")?;
    writeln!(w)?;
    for tier in Tier::all() {
        writeln!(w, "  {tier:?} — {}", tier.name())?;
        writeln!(w, "    {}", tier.description())?;
        writeln!(w, "    Stability: {}", tier.stability())?;
        writeln!(w)?;
    }
    writeln!(w, "  Assignment protocol (per AFM-0011):")?;
    writeln!(
        w,
        "    Ask \"Does this decision define <tier characteristic>?\" working"
    )?;
    writeln!(
        w,
        "    from S downward. The first YES wins. The leverage hierarchy is"
    )?;
    writeln!(
        w,
        "    Meadows-aligned: S (Paradigm) > A (Goals) > B (Self-Org) >"
    )?;
    writeln!(
        w,
        "    C (Design) > D (Parameters). Higher tiers print first in"
    )?;
    writeln!(
        w,
        "    --context output, exploiting LLM primacy bias so foundational"
    )?;
    writeln!(w, "    constraints precede implementation details.")?;
    writeln!(w)?;
    writeln!(w, "  Common mistakes:")?;
    writeln!(
        w,
        "    • Picking a tier by impact (\"this affects many crates\") rather"
    )?;
    writeln!(
        w,
        "      than leverage (\"this defines a system characteristic\")."
    )?;
    writeln!(
        w,
        "    • Promoting D-tier parameters because the value is critical:"
    )?;
    writeln!(
        w,
        "      a critical timeout is still a parameter (D), not a goal (A)."
    )?;
    writeln!(
        w,
        "    • Demoting S-tier paradigms because they feel \"too abstract to"
    )?;
    writeln!(
        w,
        "      enforce\": abstraction is the source of S-tier leverage."
    )?;
    writeln!(w)?;
    Ok(())
}

fn print_lifecycle(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "LIFECYCLE")?;
    writeln!(w, "─────────")?;
    writeln!(w)?;
    let statuses = [
        ("Draft", false),
        ("Proposed", false),
        ("Accepted", false),
        ("Rejected", true),
        ("Deprecated", true),
        ("Superseded by PREFIX-NNNN", true),
    ];
    for (name, terminal) in &statuses {
        let marker = if *terminal { " [terminal]" } else { "" };
        writeln!(w, "  {name}{marker}")?;
    }
    writeln!(w)?;
    writeln!(w, "  Terminal states require:")?;
    writeln!(w, "    • Move ADR to stale directory")?;
    writeln!(w, "    • Add a ## Retirement section")?;
    writeln!(w)?;
    Ok(())
}

fn print_template(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "TEMPLATE")?;
    writeln!(w, "────────")?;
    writeln!(w)?;
    writeln!(w, "  Required structure:")?;
    writeln!(w)?;
    writeln!(w, "    # PREFIX-NNNN. Title")?;
    writeln!(w, "    Date: YYYY-MM-DD")?;
    writeln!(w, "    Last-reviewed: YYYY-MM-DD")?;
    writeln!(w, "    Tier: S | A | B | C | D")?;
    writeln!(w, "    Status: Draft | Proposed | Accepted | ...")?;
    writeln!(w, "    ## Related")?;
    writeln!(w, "    ## Context")?;
    writeln!(w, "    ## Decision")?;
    writeln!(w, "    ## Consequences")?;
    writeln!(w, "    ## Retirement      (stale only)")?;
    writeln!(w)?;
    writeln!(w, "  Metadata fields (preamble, before first ## heading):")?;
    writeln!(w, "    Date              Creation date (enforced: T002)")?;
    writeln!(
        w,
        "    Last-reviewed     Most recent review date (enforced: T003)"
    )?;
    writeln!(
        w,
        "    Tier              Architectural significance S/A/B/C/D (enforced: T004)"
    )?;
    writeln!(
        w,
        "    Status            Lifecycle state (enforced: T005, T006)"
    )?;
    writeln!(
        w,
        "    Crates            Optional comma-separated crate list"
    )?;
    writeln!(w)?;
    writeln!(w, "  Related section format:")?;
    writeln!(
        w,
        "    Pipe-separated: Verb: TARGET1, TARGET2 | Verb: TARGET3"
    )?;
    writeln!(
        w,
        "    Example: Root: CHE-0001 | References: CHE-0002, CHE-0010"
    )?;
    writeln!(w)?;
    print_template_rules(w)
}

fn print_template_rules(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "  Rules:")?;
    print_rule_entries(w, catalog::TEMPLATE_RULES)?;
    print_template_rules_t016(w)
}

fn print_template_rules_t016(w: &mut impl Write) -> io::Result<()> {
    print_rule_entries(w, catalog::TEMPLATE_RULES_TAGGED)?;
    writeln!(w)?;
    print_template_parser_rules(w)
}

fn print_template_parser_rules(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "  Parser-stage rules:")?;
    print_rule_entries(w, catalog::PARSER_RULES)?;
    writeln!(w)?;
    Ok(())
}

fn print_tagged_rules(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(w, "TAGGED RULES (Decision Section)")?;
    writeln!(w, "───────────────────────────────")?;
    writeln!(w)?;
    writeln!(w, "  Format:  R1 [N]: Rule statement (7–60 words)")?;
    writeln!(w, "           R2 [N]: Next rule statement")?;
    writeln!(
        w,
        "           Multi-line rules: indent continuation ≥2 spaces"
    )?;
    writeln!(w)?;
    writeln!(w, "  [N] = Meadows leverage layer (1–12)")?;
    writeln!(w)?;
    print_leverage_table(w, config)
}

fn print_leverage_table(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(
        w,
        "    Layer  Leverage point (Meadows)                                              Tier"
    )?;
    writeln!(
        w,
        "    ─────  ─────────────────────────────────────────────────────────────────────  ────"
    )?;
    writeln!(
        w,
        "      1    The power to transcend paradigms                                        S"
    )?;
    writeln!(
        w,
        "      2    The mindset or paradigm out of which the system arises                 S"
    )?;
    writeln!(
        w,
        "      3    The goals of the system                                                 S"
    )?;
    writeln!(
        w,
        "      4    The power to add, change, evolve, or self-organize system structure     A"
    )?;
    writeln!(
        w,
        "      5    The rules of the system (incentives, punishments, constraints)          B"
    )?;
    writeln!(
        w,
        "      6    The structure of information flows (who does and does not have access)  B"
    )?;
    writeln!(
        w,
        "      7    The gain around driving positive feedback loops                         C"
    )?;
    writeln!(
        w,
        "      8    The strength of negative feedback loops                                 C"
    )?;
    writeln!(
        w,
        "      9    The lengths of delays, relative to the rate of system change            D"
    )?;
    writeln!(
        w,
        "     10    The structure of material stocks and flows                              D"
    )?;
    writeln!(
        w,
        "     11    The sizes of buffers and other stabilizing stocks, relative to flows    D"
    )?;
    writeln!(
        w,
        "     12    Constants, parameters, numbers                                          D"
    )?;
    writeln!(w)?;
    writeln!(w, "  Global ID: PREFIX-NNNN:RN:LN  (e.g., CHE-0042:R1:L5)")?;
    writeln!(w)?;
    print_tagged_rule_constraints(w, config)
}

fn print_tagged_rule_constraints(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(
        w,
        "  Constraints (signals — exceeding warrants review, not rejection):"
    )?;
    writeln!(
        w,
        "    • At least 1 tagged rule per Decision section (all statuses)"
    )?;
    writeln!(
        w,
        "    • Max rules are tier-scaled (S=15, A=12, B=10, C=8, D=6)"
    )?;
    writeln!(w, "    • IDs must be sequential (R1, R2, R3 — no gaps)")?;
    writeln!(w, "    • Each rule: 7–60 words")?;
    writeln!(w, "    • Layer must be 1–12 (Meadows leverage points)")?;
    writeln!(
        w,
        "    • Rule-tier tension: fires when the rule's layer-derived"
    )?;
    writeln!(
        w,
        "      tier has higher leverage than the ADR's tier; equal or"
    )?;
    writeln!(
        w,
        "      lower leverage passes silently. No distance tolerance"
    )?;
    writeln!(w, "      and no domain carve-outs (T019)")?;
    writeln!(w)?;

    writeln!(
        w,
        "  Tier scaling — factor multiplies the configured min_words,"
    )?;
    writeln!(
        w,
        "  max_words, and max_rules base values. The min_words column"
    )?;
    writeln!(
        w,
        "  below is the effective T015 minimum this corpus enforces:"
    )?;
    for tier in Tier::all() {
        writeln!(w, "{}", tier_scaling_row(config, *tier))?;
    }
    writeln!(w)?;
    Ok(())
}

pub(crate) fn tier_scaling_row(config: &Config, tier: Tier) -> String {
    let budgets = Budgets::resolve(config, &mut Vec::new());
    format!(
        "    {tier:?}  factor={:.1}  min_words={}  max_refs={}",
        tier.factor(),
        budgets.min_words_for(tier),
        tier.max_refs()
    )
}

fn print_relationships(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(w, "RELATIONSHIPS")?;
    writeln!(w, "─────────────")?;
    writeln!(w)?;
    writeln!(w, "  Links point toward the root of the dependency graph.")?;
    writeln!(w, "  Reverse links are computed on demand (--refs).")?;
    writeln!(w)?;
    writeln!(w, "  Permitted verbs (3):")?;
    for verb in RelVerb::permitted() {
        writeln!(w, "    {verb:<12} {}", verb.description())?;
    }
    writeln!(w)?;
    writeln!(w, "  Usage:")?;
    writeln!(w, "    • Every ADR must have ≥1 relationship")?;
    writeln!(w, "    • Tree roots use `Root: OWN-ID`")?;
    writeln!(w, "    • Root + References cannot coexist (L009)")?;
    writeln!(w, "    • Root + Supersedes may coexist")?;
    writeln!(
        w,
        "    • Supersedes requires target status = `Superseded by PREFIX-NNNN`"
    )?;
    writeln!(w)?;
    print_relationship_tree_model(w, config)
}

fn print_relationship_tree_model(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(
        w,
        "  Reference ordering — first References target = structural parent:"
    )?;
    writeln!(w, "    Per the parent-edge tree model (AFM-0020), every")?;
    writeln!(
        w,
        "    non-Root ADR is anchored in the tree by the FIRST target"
    )?;
    writeln!(
        w,
        "    listed in its `References:` field. Other forwards (additional"
    )?;
    writeln!(
        w,
        "    References, Refines, Supersedes) are secondary citations and"
    )?;
    writeln!(w, "    do not create parent edges.")?;
    writeln!(w)?;
    writeln!(
        w,
        "    List the most specialized applicable parent first, then add"
    )?;
    writeln!(
        w,
        "    foundation citations after. The reference whose removal would"
    )?;
    writeln!(w, "    most invalidate this ADR's decision ranks first.")?;
    writeln!(w)?;
    writeln!(w, "  Root assignment (--context):")?;
    writeln!(
        w,
        "    Each ADR's root is found by walking the parent edge upward"
    )?;
    writeln!(
        w,
        "    until a Root ADR is reached. Non-Accepted parents (Draft,"
    )?;
    writeln!(
        w,
        "    Proposed) are advisory waypoints — the chain still flows"
    )?;
    writeln!(
        w,
        "    through them (L012 warns). Cycles and chains terminating at"
    )?;
    writeln!(w, "    a non-root land in the Unclaimed group.")?;
    writeln!(w)?;
    writeln!(w, "  Cross-domain parents:")?;
    writeln!(
        w,
        "    A first References target in a different domain triggers L011."
    )?;
    writeln!(
        w,
        "    Suppress with `Parent-cross-domain: PREFIX-NNNN — reason` in"
    )?;
    writeln!(
        w,
        "    the preamble. The suppression is exact-match: a stale ID will"
    )?;
    writeln!(w, "    not silence L011.")?;
    writeln!(w)?;
    let foundation_prefixes: Vec<&str> = config
        .domains
        .iter()
        .filter(|d| d.foundation)
        .map(|d| d.prefix.as_str())
        .collect();
    if !foundation_prefixes.is_empty() {
        let foundation_list = foundation_prefixes.join(", ");
        writeln!(
            w,
            "    Foundation roots ({foundation_list}) appear before domain roots"
        )?;
        writeln!(
            w,
            "    in --context output, sorted by minimum layer then ADR number."
        )?;
        writeln!(w)?;
    }
    writeln!(w, "  Legacy verbs (produce warnings):")?;
    for verb in RelVerb::legacy() {
        let migration = verb.migration().unwrap_or("remove");
        writeln!(w, "    {verb:<15} → {migration}")?;
    }
    writeln!(w)?;
    Ok(())
}

fn print_naming(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "NAMING")?;
    writeln!(w, "──────")?;
    writeln!(w)?;
    writeln!(w, "  Rules:")?;
    print_rule_entries(w, catalog::NAMING_RULES)?;
    writeln!(w)?;
    Ok(())
}

fn print_link_rules(w: &mut impl Write) -> io::Result<()> {
    writeln!(w, "LINK RULES")?;
    writeln!(w, "──────────")?;
    writeln!(w)?;
    writeln!(w, "  Rules:")?;
    print_rule_entries(w, catalog::LINK_RULES)?;
    writeln!(w)?;
    Ok(())
}

fn print_stale(w: &mut impl Write, config: &Config) -> io::Result<()> {
    writeln!(w, "STALE DIRECTORY")?;
    writeln!(w, "───────────────")?;
    writeln!(w)?;
    writeln!(w, "  Path: {}/", config.stale.directory)?;
    writeln!(w, "  ADRs in terminal states are moved here.")?;
    writeln!(w)?;
    writeln!(w, "  Stub policy (AFM-0022): a stale ADR reduces to")?;
    writeln!(w, "    • the preamble fields,")?;
    writeln!(w, "    • an optional `## Related` containing only")?;
    writeln!(w, "      `Supersedes:` edges (forward lineage; the")?;
    writeln!(w, "      reverse direction lives in the `Status:` field),")?;
    writeln!(w, "    • a `## Retirement` section (≥7 words).")?;
    writeln!(w)?;
    writeln!(w, "  When moving an ADR to stale, delete `## Context`,")?;
    writeln!(w, "  `## Decision`, `## Consequences`, and any")?;
    writeln!(w, "  `References:` lines in the same commit; git history")?;
    writeln!(w, "  preserves the prior content.")?;
    writeln!(w)?;
    writeln!(
        w,
        "  Lint coverage on the stale lifecycle and on stale stubs:"
    )?;
    print_rule_entries(w, catalog::STALE_RULES)?;
    writeln!(w, "    T007/T008/T009/T010/T016 are skipped on stale")?;
    writeln!(w)?;
    Ok(())
}

pub(crate) fn overrides_section(config: &Config) -> Option<String> {
    let rows: Vec<String> = config
        .rules
        .iter()
        .filter(|rule| !rule.params.is_empty())
        .map(|rule| {
            let pairs: Vec<String> = rule
                .params
                .iter()
                .map(|(key, value)| format!("{key}={value}"))
                .collect();
            format!("  {}  {}", rule.id, pairs.join(", "))
        })
        .collect();
    if rows.is_empty() {
        return None;
    }
    Some(format!(
        "PARAMETER OVERRIDES\n───────────────────\n\n{}",
        rows.join("\n")
    ))
}

fn print_overrides(w: &mut impl Write, config: &Config) -> io::Result<()> {
    if let Some(section) = overrides_section(config) {
        writeln!(w, "{section}")?;
        writeln!(w)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Forbidden phrases from the pre-Tree-Model documentation.
    /// Defined in the test module so they don't leak into the scan
    /// range of `print_relationships`/`print_link_rules` source.
    const NEGATIVE_CANARY_TERMS: &[&str] = &[
        "first-root-referenced",
        "BFS proximity",
        "BFS depth",
        "breadth-first sweep",
    ];

    fn make_config() -> Config {
        toml::from_str(
            r#"
[corpus]
root = "docs/adr"

[stale]
directory = "stale"

[[domains]]
prefix = "COM"
name = "Common"
directory = "common"
description = "Cross-cutting design principles."
crates = []
foundation = true

[[domains]]
prefix = "CHE"
name = "Cherry"
directory = "cherry"
description = "Architecture decisions."
crates = ["example-core"]

[[rules]]
id = "T015"
params = { min_words = 7, max_words = 50 }
"#,
        )
        .unwrap()
    }

    fn relationships_source(src: &str) -> &str {
        let start = src
            .find("fn print_relationships")
            .expect("print_relationships exists");
        let end = src.find("fn print_naming").expect("print_naming exists");
        &src[start..end]
    }

    struct FailingWriter;

    impl Write for FailingWriter {
        fn write(&mut self, _buf: &[u8]) -> io::Result<usize> {
            Err(io::Error::new(io::ErrorKind::BrokenPipe, "broken pipe"))
        }

        fn flush(&mut self) -> io::Result<()> {
            Err(io::Error::new(io::ErrorKind::BrokenPipe, "broken pipe"))
        }
    }

    #[test]
    fn setup_guide_returns_err_on_broken_writer() {
        let err = print_setup_guide(&mut FailingWriter)
            .expect_err("a failing writer must surface as Err, never a panic");
        assert_eq!(
            err.kind(),
            io::ErrorKind::BrokenPipe,
            "the underlying writer error must reach the caller unchanged so \
             main can map it to the AFM-0003:R1 infrastructure exit code"
        );
    }

    #[test]
    fn governance_returns_err_on_broken_writer() {
        let config = make_config();
        let err = print_governance(&mut FailingWriter, &config)
            .expect_err("a failing writer must surface as Err, never a panic");
        assert_eq!(
            err.kind(),
            io::ErrorKind::BrokenPipe,
            "the underlying writer error must reach the caller unchanged so \
             main can map it to the AFM-0003:R1 infrastructure exit code"
        );
    }

    #[test]
    fn setup_guide_does_not_panic() {
        let mut sink = Vec::new();
        print_setup_guide(&mut sink).expect("writing into a Vec cannot fail");
        assert!(!sink.is_empty(), "the setup guide must render content");
    }

    #[test]
    fn governance_does_not_panic() {
        let config = make_config();
        let mut sink = Vec::new();
        print_governance(&mut sink, &config).expect("writing into a Vec cannot fail");
        assert!(
            !sink.is_empty(),
            "the governance reference must render content"
        );
    }

    #[test]
    fn overrides_section_shown_when_params_exist() {
        let config = make_config();
        let section =
            overrides_section(&config).expect("T015 carries params, so the section renders");
        assert!(
            section.starts_with("PARAMETER OVERRIDES\n───────────────────\n\n"),
            "the overrides section must carry its heading: {section}"
        );
        assert!(
            section.contains("  T015  "),
            "the rule carrying params must be listed: {section}"
        );
        assert!(
            section.contains("min_words=7"),
            "each overridden parameter must be rendered as key=value: {section}"
        );
        assert!(
            section.contains("max_words=50"),
            "each overridden parameter must be rendered as key=value: {section}"
        );
    }

    #[test]
    fn overrides_section_hidden_when_no_params() {
        let config: Config = toml::from_str(
            r#"
[corpus]
root = "docs/adr"

[stale]
directory = "stale"

[[domains]]
prefix = "CHE"
name = "Cherry"
directory = "cherry"
description = "Test"
crates = []
"#,
        )
        .unwrap();
        assert!(
            overrides_section(&config).is_none(),
            "no rule carries params, so the overrides section must be omitted \
             entirely rather than rendered empty"
        );
    }

    #[test]
    fn relationships_contains_reference_ordering_guidance() {
        let src = include_str!("guidelines.rs");
        let scan = relationships_source(src);
        for needle in [
            "first References target = structural parent",
            "walking the parent edge upward",
            "advisory waypoints",
            "Parent-cross-domain",
            "Foundation roots",
        ] {
            assert!(
                scan.contains(needle),
                "print_relationships must document `{needle}`, or the \
                 parent-edge tree model (AFM-0020) is undocumented in \
                 governance output"
            );
        }
    }

    #[test]
    fn relationships_no_stale_pre_tree_model_terms() {
        let src = include_str!("guidelines.rs");
        let start = src
            .find("fn print_relationships")
            .expect("print_relationships exists");
        let end = src.find("fn print_stale").expect("print_stale exists");
        let scan = &src[start..end];
        for forbidden in NEGATIVE_CANARY_TERMS {
            assert!(
                !scan.contains(forbidden),
                "stale pre-Tree-Model term `{forbidden}` reappeared in \
                 print_relationships/print_link_rules source range"
            );
        }
    }

    #[test]
    fn foundation_prefixes_derived_from_config() {
        let src = include_str!("guidelines.rs");
        assert!(
            relationships_source(src).contains("foundation_list"),
            "print_relationships must derive foundation prefixes from config"
        );
        assert!(
            !src.contains("\"COM, RST, SEC\""),
            "foundation prefixes must not be hardcoded"
        );
    }

    #[test]
    fn tier_scaling_table_derived_from_model() {
        let src = include_str!("guidelines.rs");
        let start = src
            .find("pub(crate) fn tier_scaling_row")
            .expect("tier_scaling_row exists");
        let end = src[start..]
            .find("fn print_relationships")
            .expect("tier_scaling_row is followed by print_relationships")
            + start;
        let scan = &src[start..end];
        assert!(
            scan.contains("tier.factor()"),
            "tier scaling table must use Tier::factor()"
        );
        assert!(
            scan.contains("budgets.min_words_for(tier)"),
            "the tier scaling table MUST source min_words from the configured \
             T015 budget, not from the fixed Tier::min_words table"
        );
        assert!(
            !scan.contains("tier.min_words()"),
            "the tier scaling table MUST NOT read the fixed legacy \
             Tier::min_words table; enforcement does not use it"
        );
        assert!(
            scan.contains("tier.max_refs()"),
            "tier scaling table must use Tier::max_refs()"
        );
        let needle = format!("println!(\"    {}  factor=", "S");
        assert!(
            !src.contains(&needle),
            "tier scaling values must not be hardcoded in println"
        );
    }

    #[test]
    fn t016_registry_text_matches_shipped_warning_severity() {
        let src = include_str!("rules/catalog.rs");
        let start = src
            .find("const T016: RuleEntry")
            .expect("T016 catalog entry exists");
        let end = src[start..]
            .find("const T019: RuleEntry")
            .expect("the T016 entry is followed by the T019 entry")
            + start;
        let scan = &src[start..end];
        assert!(
            !scan.contains("is an error"),
            "AFM-0003:R2 and rules/template.rs both expose the T016 layer \
             finding as a WARNING; the generated text must not claim error"
        );
        assert!(
            scan.contains("does not match the required"),
            "the generated T016 guidance must document the malformed \
             rule-shaped line check, or a shipped diagnostic is invisible"
        );
    }

    #[test]
    fn t019_constraint_text_states_the_asymmetric_bound() {
        let src = include_str!("guidelines.rs");
        let start = src
            .find("• Rule-tier tension")
            .expect("the constraints list carries a T019 bullet");
        let end = src[start..]
            .find("(T019)")
            .expect("the T019 bullet is tagged with its rule id")
            + start;
        let scan = &src[start..end];
        assert!(
            !scan.contains("1 rank") && !scan.contains("2 ranks"),
            "AFM-0011 accepted an ASYMMETRIC T019 bound with no distance \
             carve-out; the obsolete symmetric-distance wording would tell \
             authors a corpus shape passes when the linter warns"
        );
        assert!(
            scan.contains("higher leverage than the ADR's tier"),
            "the T019 bullet must state the asymmetric condition \
             (rule_rank < adr_rank) that the implementation enforces"
        );
    }
}
